export const EnglishName: { [key: string]: string } = {
  ゲッコー: "GEKKO",
  フェイド: "FADE",
  ブリーチ: "BREACH",
  デッドロック: "DEADLOCK",
  "KAY/O": "KAY/0",
  スカイ: "SKY",
  サイファー: "CYPHER",
  ソーヴァ: "SOVA",
  キルジョイ: "KILLJOY",
  ハーバー: "HARBOR",
  ヴァイパー: "VIPER",
  フェニックス: "PHOENIX",
  ブリムストーン: "BRIMSTONE",
  アイソ: "ISO",
  クローヴ: "CLOVE",
  ネオン: "NEON",
  ヨル: "YORU",
  セージ: "SAGE",
  レイナ: "REYNA",
  オーメン: "OMEN",
  ジェット: "JETT",
  レイズ: "RAZE",
  チェンバー: "CHAMBER",
  アストラ: "ASTRA",
};
